### ISSUE TITLE
Add a .gitattributes file for consistent line endings

### ISSUE THREAD

**Issue by SoullessWaffle** [Blocklevel/bcli#5]
This should eliminate a lot of potential issues with line endings between the different platforms.

**Comment by MatteoGabriele** [comment]
@SoullessWaffle you mean in the repository itself on in the generated templates?

**Comment by SoullessWaffle** [comment]
I meant in the repo itself, but it's probably a good idea to add it to the projects too.
I guess that part is covered by blue though.

**Comment by MatteoGabriele** [comment]
Yeah exactly. For the repository it's fine, but not for the generated Blue template: for now it's just a mock
